#!/bin/sh

# PROVIDE: Scryptic
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# Scryptic_enable (bool): Set to NO by default. Set this variable to YES if you want to enable Scryptic service.
# Scryptic_config (path): Set to /usr/local/etc/Scryptic.conf by default.
# Scryptic_user:  The user account Scryptic daemon runs as. It uses 'root' user by default.
# Scryptic_group: The group account Scryptic daemon runs as. It uses 'wheel' group by default.
# Scryptic_datadir (str): Default to "/var/db/Scryptic". Base data directory.

. /etc/rc.subr

name=Scryptic
rcvar=Scryptic_enable

: ${Scryptic_enable:=NO}
: ${Scryptic_config=/usr/local/etc/Scryptic.conf}
: ${Scryptic_datadir=/var/db/Scryptic}
: ${Scryptic_user="root"}
: ${Scryptic_group="wheel"}

required_files=${Scryptic_config}
command=/usr/local/bin/Scrypticd
Scryptic_chdir=${Scryptic_datadir}
pidfile="${Scryptic_datadir}/Scrypticd.pid"
stop_cmd=Scryptic_stop
command_args="-conf=${Scryptic_config} -datadir=${Scryptic_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

Scryptic_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${Scryptic_datadir}
	[ $? -eq 0 ] && chown -R ${Scryptic_user}:${Scryptic_group} ${Scryptic_datadir}
}

Scryptic_prestart()
{
	if [ ! -d "${Scryptic_datadir}/." ]; then
		Scryptic_create_datadir || return 1
	fi
}

Scryptic_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

Scryptic_stop()
{
    Scryptic_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${Scryptic_config} -datadir=${Scryptic_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
